title: Mi Portafolio
description: Portafolio profesional con TDD y ORM en JSON
theme: minima
plugins:
  - jekyll-feed

# Configuraci贸n ORM
orm:
  data_file: "_data/projects.json"

# Configuraci贸n personal
author:
  name: Washington Olarte Velasquez
  email: 23976963@continental.edu.pe
  github: Wachifr
  

# Configuraci贸n de construcci贸n
markdown: kramdown
permalink: pretty
